apiVersion: 1
datasources:
  # Tempo datasource for distributed traces
  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo-query-frontend.tempo.svc.cluster.local:3200

  # VictoriaMetrics datasource for metrics
  - name: VictoriaMetrics
    type: victoriametrics-metrics-datasource
    uid: victoriametrics
    url: http://vm-vmselect.victoria-metrics.svc.cluster.local:8481/select/0/prometheus
    access: proxy
    isDefault: false
    jsonData:
      httpMethod: POST
      timeInterval: 15s

  # OpenObserve datasource for logs
  - name: OpenObserve
    type: grafana-openobserve-datasource
    uid: openobserve
    url: http://o2-openobserve-router.openobserve.svc:5080
    access: proxy
    isDefault: false
    jsonData:
      database: SkiesDota  # Organization name
    secureJsonData:
      # Injected by Ansible
      user: "{{ openobserve_user }}"
      password: "{{ openobserve_password }}"
