# Grafana HA Configuration
# Required secrets: see required-secrets.yaml in this directory.

replicas: 3
podDisruptionBudget:
  minAvailable: 2
resources:
  limits:
    cpu: 500m
    memory: 768Mi
  requests:
    cpu: 250m
    memory: 512Mi
admin:
  existingSecret: grafana-admin-creds
  userKey: user
  passwordKey: password
envValueFrom:
  GF_DATABASE_USER:
    secretKeyRef:
      name: grafana-db-creds
      key: username
  GF_DATABASE_PASSWORD:
    secretKeyRef:
      name: grafana-db-creds
      key: password
  ZO_ROOT_USER_EMAIL:
    secretKeyRef:
      name: grafana-datasource-openobserve-root-creds
      key: ZO_ROOT_USER_EMAIL
  ZO_ROOT_USER_PASSWORD:
    secretKeyRef:
      name: grafana-datasource-openobserve-root-creds
      key: ZO_ROOT_USER_PASSWORD
env:
  GF_DATABASE_TYPE: postgres
  GF_DATABASE_HOST: grafana-postgres-rw.grafana.svc.cluster.local
  GF_DATABASE_NAME: grafana
  GF_DATABASE_SSL_MODE: disable
  GF_SESSION_PROVIDER: database
  GF_PLUGINS_PREINSTALL_SYNC: victoriametrics-metrics-datasource
  GF_SESSION_COOKIE_MAX_AGE: "315360000"
  GF_SECURITY_LOGIN_REMEMBER_DAYS: "3650"
  GF_AUTH_LOGIN_MAXIMUM_INACTIVE_LIFETIME_DURATION: 3650d
  GF_AUTH_LOGIN_MAXIMUM_LIFETIME_DURATION: 3650d
  GF_SECURITY_COOKIE_SECURE: "true"
  GF_SECURITY_COOKIE_SAMESITE: lax
  GF_LOG_LEVEL: warn
  GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: grafana-openobserve-datasource
extraInitContainers:
  - name: download-openobserve-plugin
    image: alpine:latest
    command: ["/bin/sh", "-c"]
    args:
      - |
        echo "Installing Custom OpenObserve Plugin..."
        WORKDIR="/var/lib/grafana/plugins"
        mkdir -p $WORKDIR
        
        wget -O /tmp/plugin.zip https://github.com/LinPr/grafana-openobserve-datasource/releases/download/v1.3.0/grafana-openobserve-datasource-1.3.0.zip
        
        # Unzip into the plugins directory
        # -d specifies the target directory
        unzip -o /tmp/plugin.zip -d $WORKDIR
        
        echo "Plugin installed successfully."
    volumeMounts:
      - name: openobserve-plugin-storage
        mountPath: /var/lib/grafana/plugins
extraVolumes:
  - name: openobserve-plugin-storage
    emptyDir: {}
extraVolumeMounts:
  - name: openobserve-plugin-storage
    mountPath: /var/lib/grafana/plugins

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Tempo
        type: tempo
        uid: tempo
        url: http://tempo-query-frontend.tempo.svc.cluster.local:3200

      - name: VictoriaMetrics
        type: victoriametrics-metrics-datasource
        uid: victoriametrics
        url: http://vm-vmselect.victoria-metrics.svc.cluster.local:8481/select/0/prometheus
        access: proxy
        isDefault: false
        jsonData:
          httpMethod: POST
          timeInterval: 15s

      - name: OpenObserve
        type: grafana-openobserve-datasource
        uid: openobserve
        url: http://o2-openobserve-router.openobserve.svc.cluster.local:5080
        access: proxy
        isDefault: false
        user: ${ZO_ROOT_USER_EMAIL}
        jsonData:
          database: skies-dota
        secureJsonData:
          password: ${ZO_ROOT_USER_PASSWORD}