collections:
  - name: community.crypto
    version: ">=1.0.0"
  - name: community.general
    version: ">=1.0.0"
  - name: ansible.posix
    version: ">=1.0.0"
  - name: kubernetes.core
    version: ">=1.0.0"

roles:
  - name: geerlingguy.docker
    version: "7.6.0"
  - name: geerlingguy.firewall
    version: "2.7.0"
  - name: xanmanning.k3s
    version: "v3.6.2"