collections:
  - name: community.crypto
    version: 2.26.3
  - name: community.general
    version: 9.3.0
  - name: ansible.posix
    version: 1.6.2
  - name: kubernetes.core
    version: 5.0.0
  - name: rancherfederal.rke2_ansible
    source: https://github.com/rancherfederal/rke2-ansible.git
    type: git
    version: v2.0.0

roles:
  - name: geerlingguy.docker
    version: 8.0.0
  - name: geerlingguy.firewall
    version: 2.7.0
  - name: xanmanning.k3s
    version: v3.6.2